### ISSUE TITLE
Error occurs when there is some space in input data.

### ISSUE THREAD

**Issue by RonyK** [RonyK/SuaDB#11]
If there were some space in input string, ArrayFile input function throw NumberFormatException.
Ignore all white spaces in input file string.

Example format:
[[[(0, 100, 1),(1, 99, ),(2, , 3),(, 97, 4)],[(4, , ),(, 95, ),(9, , ),(, , )],[(9, 92, ),(9, 91, ),(, , 11),(11, 89, )],[(12, 88, 13),(, 13, 14),(14, 86, 15),(15, 85, 16)]]]

java.lang.NumberFormatException: For input string: " 100"

	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:569)
	at java.lang.Integer.parseInt(Integer.java:615)
	at suadb.record.ArrayFile.input(ArrayFile.java:474)
	at suadb.query.afl.ArrayScan.insert(ArrayScan.java:102)
	at suadb.planner.BasicUpdatePlanner.executeInputArray(BasicUpdatePlanner.java:72)
	at suadb.planner.Planner.executeUpdate(Planner.java:54)
	at suadb.server.SuaDB_3D_ABC.test_20_array_input(SuaDB_3D_ABC.java:166)

**Comment by DalsuChoi** [comment]
Fixed
